reanahub/reana-workflow-engine-serial

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/openapi_connections/reana_job_controller.json
reana_workflow_engine_serial/tasks.py
setup.py

* Publishes run progress (current step, current command) to MQ.
Depends on https://github.com/reanahub/reana-workflow-engine-serial/pull/8/files

tasks: publish run progress

---

reana_workflow_engine_serial/openapi_connections/reana_job_controller.json
reana_workflow_engine_serial/tasks.py

tasks: remove workflow_uuid from job creation req

---

reana_workflow_engine_serial/tasks.py

tasks: fixes in progress reporting

---

reana_workflow_engine_serial/tasks.py

tasks: refactor job progress reporting

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py

Connect https://github.com/reanahub/reana-workflow-controller/issues/107.

tasks: remove inputs/outputs/code directories

---

.travis.yml
run-tests.sh

travis: addition of docker image build test

---

reana_workflow_engine_serial/openapi_connections/reana_job_controller.json
reana_workflow_engine_serial/tasks.py

job-submission: add prettified_cmd and job_name

---

reana_workflow_engine_serial/openapi_connections/reana_job_controller.json
reana_workflow_engine_serial/tasks.py

Connect https://github.com/reanahub/reana-commons/issues/24

tasks: progress status renaming

---

reana_workflow_engine_serial/tasks.py

Connects https://github.com/reanahub/reana-client/issues/143

tasks: addition of parameter to disable caching

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/index.rst
docs/overview.rst
reana_workflow_engine_serial/celeryapp.py
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/version.py
run-tests.sh
setup.py

Connects https://github.com/reanahub/reana-workflow-engine-serial/issues/31
Closes #31

docs: pydocstyle fixes

---

reana_workflow_engine_serial/tasks.py

* Adds support for embedding variables inside command strings using
`$varname` or `${varname}` notation. This is an implementation based
on the Python standard library [`string.Template`](https://docs.python.org/3/library/string.html#template-strings) (closes #34).
Depends on https://github.com/reanahub/reana-commons/pull/40.

tasks: support workflow parameter interpolation

---

reana_workflow_engine_serial/tasks.py

tasks: refactor path related operations

---

reana_workflow_engine_serial/tasks.py
setup.py

Connects reanahub/reana-workflow-controller#131.

publisher: use Kombu based publisher

---

reana_workflow_engine_serial/tasks.py

tasks: renaming operational_parameters

---

CHANGES.rst
reana_workflow_engine_serial/version.py
setup.py

release: v0.4.0

---

reana_workflow_engine_serial/tasks.py

* Change of status determination by using steps with appended
input parameters. Connects https://github.com/reanahub/reana-client/issues/200
Signed-off-by: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>
Co-authored-by: Diego Rodriguez diego.rodriguez@cern.ch

tasks: status determined by expanded_workflow_json

---

Dockerfile
reana_workflow_engine_serial/celeryapp.py
reana_workflow_engine_serial/tasks.py
setup.py

Connect reanahub/reana-client#194.

tasks: add revoke handler

---

reana_workflow_engine_serial/tasks.py
setup.py

global: workflow engine independent of celery

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py

config: MOUNT_CVMFS as string

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
setup.py

* Refactors tasks.py to split up units of work.
* Adds exception catching to publish failure of workflow.
Connects https://github.com/reanahub/reana-client/issues/234

global: refactoring

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
setup.py

Connect https://github.com/reanahub/reana-cluster/issues/154

config: cvmfs_mounts boolean

---

reana_workflow_engine_serial/version.py
setup.py

installation: reana-commons with kubernetes

---

Dockerfile

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docker: slimmer image

---

reana_workflow_engine_serial/tasks.py

logging: logging format from R-Commons

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/conf.py
reana_workflow_engine_serial/version.py
setup.py

* Closes #75
Signed-off-by: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>

release: 0.5.0

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

* Addresses reanahub/reana-commons/issues/118

global: allows to set job backend and name

---

reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

Signed-off-by: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>

tasks: adds kerberos field

---

AUTHORS.rst
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

* Add target as operational option.
* Addresses #54.
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

serial: partial workflow execution

---

reana_workflow_engine_serial/utils.py

* Addresses reanahub/reana-workflow-controller/issues/269

utils: deletes experiment field from job request

---

reana_workflow_engine_serial/version.py
setup.py

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

version: post-release bump

---

reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
tests/test_utils.py

* Addresses reanahub/reana-client/issues/355

tasks: allow to execute workflow from specified step

---

reana_workflow_engine_serial/tasks.py

task: proper log msg in case of failures

---

reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

* Addresses reanahub/reana-job-controller/issues/238

global: allows to use unpacked images

---

reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py

Closes reanahub/docs.reana.io#18.

config: clean unused config

---

reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

Add field for grid proxy to serial workflow. Add `proxy: true` to reana.yaml to get proxy certificate.
closes reanahub/reana#256

tasks: add proxy field

---

CHANGES.rst
README.rst
docs/conf.py
pytest.ini
reana_workflow_engine_serial/__init__.py
reana_workflow_engine_serial/config.py
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_utils.py

global: Black support

---

.flake8
.github/workflows/ci.yml
Dockerfile
MANIFEST.in
run-tests.sh
setup.py

addresses https://github.com/reanahub/reana/issues/450

ci: add hadolint and flake8 linters

---

reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
requirements.txt
setup.py

* Uses REANA-Commons decorator to handle termination signals in the
workflow engine container by notifying the system about the failure
and registering the workflow as failed.
Addresses reanahub/reana#478

global: handle termination signals

---

CHANGES.rst
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
requirements.txt
setup.py

Closes https://github.com/reanahub/reana-job-controller/issues/304.

global: harmonise job command treatment

---

reana_workflow_engine_serial/version.py
requirements.txt
setup.py

release: 0.8.0a2

---

CHANGES.rst
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

publish workflow running status early

---

CHANGES.rst
reana_workflow_engine_serial/version.py
requirements.txt
setup.py

- installation: bump shared modules
- installation: bump all dependencies
- release: 0.9.1

release: 0.9.1

---

CHANGES.rst
Dockerfile
reana_workflow_engine_serial/version.py
requirements.txt
setup.py

release: 0.9.2

---

reana_workflow_engine_serial/utils.py

Closes reanahub/reana-workflow-controller#546

fix(progress): handle stopped jobs (#195)

---

AUTHORS.md
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py

This pull request add support for user configurable parameters in the Compute4PUNCH backend. See https://github.com/reanahub/reana-job-controller/pull/430.

feat(api) Add support for the Compute4PUNCH backend

---

AUTHORS.md
reana_workflow_engine_serial/tasks.py
reana_workflow_engine_serial/utils.py
requirements.txt
setup.py

feat(tasks): pass resource requests and limits to job-controller
